export const GET_REQUEST = "GET_REQUEST";
export const GET_FAILURE = "GET_FAILURE";

export const GET_ALL_SONGS_SUCCESS = "GET_ALL_SONGS_SUCCESS";

export const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS";

export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";

export const SET_CURRENT_PLAYING = "SET_CURRENT_PLAYING";

export const SET_CURRENT_SONG_DATA = "SET_CURRENT_SONG_DATA";

export const SAVE_TO_BEFORE_FILTER = "SAVE_TO_BEFORE_FILTER";

export const STORE_USER_DATA = "STORE_USER_DATA";

export const ADD_NEW_PLAYLIST = "ADD_NEW_PLAYLIST";

export const GET_ALL_PLAYLIST = "GET_ALL_PLAYLIST";

export const ALREADY_LOGGED_IN = "ALREADY_LOGGED_IN";

export const ADD_SONG_TO_PLAYLIST = "ADD_SONG_TO_PLAYLIST";
